In [4]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

In [5]:
df = pd.read_csv('Downloads/zoo.csv')

df.head()

animal_name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
0    aardvark     1         0     0     1         0        0         1   
1    antelope     1         0     0     1         0        0         0   
2        bass     0         0     1     0         0        1         1   
3        bear     1         0     0     1         0        0         1   
4        boar     1         0     0     1         0        0         1   

   toothed  backbone  breathes  venomous  fins  legs  tail  domestic  catsize  \
0        1         1         1         0     0     4     0         0        1   
1        1         1         1         0     0     4     1         0        1   
2        1         1         0         0     1     0     1         0        0   
3        1         1         1         0     0     4     0         0        1   
4        1         1         1         0     0     4     1         0        1   

   class_type  
0           1  
1           1  
2           4  
3           1  
4           1

In [9]:
factors = list(df.columns)
print(factors)

['animal_name', 'hair', 'feathers', 'eggs', 'milk', 'airborne', 'aquatic', 'predator', 'toothed', 'backbone', 'breathes', 'venomous', 'fins', 'legs', 'tail', 'domestic', 'catsize', 'class_type']


In [10]:
factors.remove('class_type')
factors.remove('animal_name')

print(factors)

['hair', 'feathers', 'eggs', 'milk', 'airborne', 'aquatic', 'predator', 'toothed', 'backbone', 'breathes', 'venomous', 'fins', 'legs', 'tail', 'domestic', 'catsize']


In [11]:
X = df[factors].values
Y = df.class_type


print(X.shape)
print(Y.shape)

(101, 16)
(101,)


In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.8, random_state = 0)



In [13]:
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(20, 16)
(20,)
(81, 16)
(81,)


In [15]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors = 2)

knn.fit(X_train, Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=2, p=2,
                     weights='uniform')

In [16]:
X_new=np.array([[1,0,1,0,1,0,1,0,1,0,1,0,0,1,1,0]])

In [17]:
pred = knn.predict(X_new)
print(pred)

[4]


In [18]:
print("training accuracy :", knn.score(X_train, Y_train))
print("testing accuracy :", knn.score(X_test, Y_test))

training accuracy : 0.85
testing accuracy : 0.7654320987654321


In [19]:
from sklearn.naive_bayes import GaussianNB

In [20]:
nb = GaussianNB()
nb.fit(X_train, Y_train)
print("training accuracy :", nb.score(X_train, Y_train))
print("testing accuracy :", nb.score(X_test, Y_test))

training accuracy : 1.0
testing accuracy : 0.8765432098765432


In [22]:
re = pd.read_csv('Downloads/class.csv')

re.head()

Class_Number  Number_Of_Animal_Species_In_Class Class_Type  \
0             1                                 41     Mammal   
1             2                                 20       Bird   
2             3                                  5    Reptile   
3             4                                 13       Fish   
4             5                                  4  Amphibian   

                                        Animal_Names  
0  aardvark, antelope, bear, boar, buffalo, calf,...  
1  chicken, crow, dove, duck, flamingo, gull, haw...  
2    pitviper, seasnake, slowworm, tortoise, tuatara  
3  bass, carp, catfish, chub, dogfish, haddock, h...  
4                             frog, frog, newt, toad

In [23]:
X_new=np.array([[1,0,1,0,1,0,1,0,1,0,1,0,0,1,1,0]])
pred = nb.predict(X_new)
re.loc[pred-1,'Class_Type']

6    Invertebrate
Name: Class_Type, dtype: object

In [24]:
X_new=np.array([[1,0,1,0,1,0,1,0,1,0,1,0,0,1,1,0]])
pred = knn.predict(X_new)
re.loc[pred-1,'Class_Type']

3    Fish
Name: Class_Type, dtype: object

In [26]:
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier()
rfc.fit(X_train, Y_train)
print("training accuracy :", rfc.score(X_train, Y_train))
print("testing accuracy :", rfc.score(X_test, Y_test))

training accuracy : 0.95
testing accuracy : 0.8765432098765432


G:\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [27]:
X_new=np.array([[1,0,1,0,1,0,1,0,1,0,1,0,0,1,1,0]])
pred = rfc.predict(X_new)
re.loc[pred-1,'Class_Type']

3    Fish
Name: Class_Type, dtype: object

In [28]:
from sklearn.metrics import confusion_matrix

expected = rfc.predict(X_test)
predicted =Y_test
results = confusion_matrix(expected, predicted)
print(results)


[[33  0  1  0  0  0  1]
 [ 0 15  2  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  2 12  0  0  0]
 [ 0  0  0  0  3  0  2]
 [ 0  0  0  0  0  5  2]
 [ 0  0  0  0  0  0  3]]


In [29]:
from sklearn.metrics import confusion_matrix

expected = nb.predict(X_test)
predicted =Y_test
results = confusion_matrix(expected, predicted)
print(results)


[[28  0  0  0  0  0  0]
 [ 2 15  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 3  0  3 12  0  0  0]
 [ 0  0  1  0  3  0  0]
 [ 0  0  0  0  0  5  0]
 [ 0  0  1  0  0  0  8]]


In [ ]:
from sklearn.metrics import confusion_matrix

expected = knn.predict(X_test)
predicted =Y_test
results = confusion_matrix(expected, predicted)
print(results)
